<?php
    define('DATE_TIME_FORMAT', 'Y-m-d H:i:s');
    define('CURRENT_TIME_ZONE', 7);
    define("PAGINATE",20);
    define('DATE_TIME_REGEX_PATTERN', '^(\d){2}\-(\d){2}\-(\d){2} (\d){2}\:(\d){2}\:(\d){2}$');
    define('GMT_0', 0);
    define("GMT_1_POS", 1);
    define("GMT_2_POS", 2);
    define("GMT_3_POS", 3);
    define("GMT_4_POS", 4);
    define("GMT_5_POS", 5);
    define("GMT_6_POS", 6);
    define("GMT_7_POS",7);
    define("GMT_8_POS", 8);
    define("GMT_9_POS", 9);
    define("GMT_10_POS", 10);
    define("GMT_11_POS", 11);
    define("GMT_12_POS", 12);
    define("GMT_1_NEG", -1);
    define("GMT_2_NEG", -2);
    define("GMT_3_NEG", -3);
    define("GMT_4_NEG", -4);
    define("GMT_5_NEG", -5);
    define("GMT_6_NEG", -6);
    define("GMT_7_NEG", -7);
    define("GMT_8_NEG", -8);
    define("GMT_9_NEG", -9);
    define("GMT_10_NEG", -10);
    define("GMT_11_NEG", -11);
    define("DEFAULT_PASSWORD_RESET","1A2b3c4d5e6f");
//https://regex101.com/r/5X3Pjl/3